### ISSUE TITLE
`username_template` not recognized

### ISSUE THREAD

**Issue by akaihola** [yuvipanda/ldapauthenticator#6]
The `README.md` file says:
>Template to use to generate the full dn for a user from the human readable username. For example, if users in your LDAP database have DN of the form uid=Yuvipanda,ou=people,dc=wikimedia,dc=org where Yuvipanda is the username, you would set this config item to be:
>
>`c.LDAPAuthenticator.username_template = 'uid={username},ou=people,dc=wikimedia,dc=org'`
>
>The {username} is expanded into the username the user provides.

However, when I set this option and start JupyterHub, I get:

>[W 2016-01-26 10:13:11.050 JupyterHub configurable:162] Config option `username_template` not recognized by `LDAPAuthenticator`, do you mean one of : `username_pattern ,username_map ,bind_dn_template`

**Comment by yuvipanda** [comment]
Hey! We changed it to 'bind_dn_template' but forgot to fully update the
README. I've done so now! Try using bind_dn_template instead of
username_template?

Thanks, and sorry for the confusion!

On Tue, Jan 26, 2016 at 2:15 AM, Antti Kaihola <notifications@github.com>
wrote:

> The READMEmd file says:
>
> Template to use to generate the full dn for a user from the human readable
> username For example, if users in your LDAP database have DN of the form
> uid=Yuvipanda,ou=people,dc=wikimedia,dc=org where Yuvipanda is the
> username, you would set this config item to be:
>
> cLDAPAuthenticatorusername_template =
> 'uid={username},ou=people,dc=wikimedia,dc=org'
>
> The {username} is expanded into the username the user provides
>
> However, when I set this option and start JupyterHub, I get:
>
> [W 2016-01-26 10:13:11050 JupyterHub configurable:162] Config option
> username_template not recognized by LDAPAuthenticator, do you mean one of
> : username_pattern ,username_map ,bind_dn_template
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yuvipanda/ldapauthenticator/issues/6>.
>



-- 
Yuvi Panda T
http://yuvi.in/blog
