### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by akaihola** [yuvipanda/ldapauthenticator#7]
jupyterhub-ldapauthenticator is not available in the [PyPI index](https://pypi.python.org/pypi?%3Aaction=search&term=ldapauthenticator&submit=search). It does have a good `setup.py` script, so fixing this is just a matter of registering and uploading it.

**Comment by yuvipanda** [comment]
Have done so! https://pypi.python.org/pypi/jupyterhub-ldapauthenticator/1.0. Thanks for reporting, and sorry about the delay!
